### ISSUE TITLE
Unable to build 

### ISSUE THREAD

**Issue by mmuru** [datafusion-contrib/datafusion-python#18] opened 2022-01-15 07:05 UTC
On MacOS and python 3.7

after clone the project, I tried to build it but failed with following
 
````
maturin develop
🍹 Building a mixed python/rust project
💥 maturin failed
  Caused by: Cargo metadata failed. Does your crate compile with `cargo build`?
  Caused by: `cargo metadata` exited with an error:     Updating crates.io index
error: failed to select a version for the requirement `datafusion = "=6.0.0"`
candidate versions found which didn't match: 5.0.0, 4.0.0, 3.0.0, ...
location searched: crates.io index
````

Please, let me know how to fix the build issue.  

@houqp: 
I noticed that README.md points the previous repo and it should be updated.

**Comment by mmuru** [comment] 2022-01-20 03:54
@houqp & @Jimexist: Can you help me to unblock this build issue? Thanks.

**Comment by houqp** [comment] 2022-01-20 04:52
Did you have a local path override for the datafusion dependency? version 6.x is available on creates.io: https://crates.io/crates/datafusion/versions.

Good catch on the readme and yes we should get that fixed. PRs welcome :)

**Comment by mmuru** [comment] 2022-01-20 23:04
@houqp: Actually, the issue was rustc version must be > 1.56.1. I had to upgrade rustc version to latest (1.58.1) and afterward s I was able to build datafusion-python package. 
Sure, I will create a PR for documentation fix.  

We noticed df.collect method performance is slow and I would like to discuss with you. Do you have an email I could reach out to you?

**Comment by houqp** [comment] 2022-01-21 02:19
@mmuru for performance related issue, it's best if you can send a reproducible sample code to apache/arrow-datafusion repo and tag me so other people from the community can jump in to help as well.

**Comment by houqp** [comment] 2022-01-22 20:09
@mmuru are you able to reproduce the performance issue using just Rust code?

**Comment by messense** [comment] 2022-01-26 07:00
> Actually, the issue was rustc version must be > 1.56.1. I had to upgrade rustc version to latest (1.58.1) and afterward s I was able to build datafusion-python package. Sure, I will create a PR for documentation fix.

The error message from maturin is quite confusing and needs improvement, I've opened https://github.com/PyO3/maturin/issues/787 to track this.

**Comment by Jimexist** [comment] 2022-02-25 12:27
since this isn't an issue with this crate, closing this.

**Closed by Jimexist** 2022-02-25 12:27 UTC
